version: '3.8'

services:
  db:
    image: postgres:15.1
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: test123
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "postgres_data:/var/lib/postgresql/data"

  pgAdmin:
    image: dpage/pgadmin4:6.16
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@cargo.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    depends_on:
      - db

  car-go:
    image: s22630/car-go-backend:latest
    ports:
      - 8083:8083
    depends_on:
      - db
