addSbtPlugin("dev.guardrail" % "sbt-guardrail" % "0.75.1")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.4.6")
addSbtPlugin("com.github.sbt" % "sbt-native-packager" % "1.9.4")
addSbtPlugin("org.openapitools" % "sbt-openapi-generator" % "5.0.1")
addSbtPlugin("io.github.davidmweber" % "flyway-sbt" % "7.4.0")
