name: Deploy to heroku

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build with sbt-docker
        run: sbt docker:publishLocal
      - name: Login to Heroku
        run: heroku login -i
      - name: Push to Heroku Container Registry
        run: heroku container:push web -a car-go-backend
      - name: Release
        run: heroku container:release web -a car-go-backend