#name: Flyway Migration
#
#on:
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Install SBT
#        uses: actions/setup-java@v1
#        with:
#          java-version: 17
#      - name: Run Flyway Migrations
#        env:
#          DB_URL: ${{ secrets.DB_URL }}
#          DB_PASS: ${{ secrets.DB_PASS }}
#          DB_USER: ${{ secrets.DB_USER }}
#        run: sbt flywayMigrate
